"""baseline

Revision ID: face92e74fe7
Revises: 
Create Date: 2026-05-11 16:53:59.419966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'face92e74fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    op.drop_index(op.f('idx_notifications_unread'), table_name='notification_log', postgresql_where='(read_at IS NULL)')
    op.drop_index(op.f('idx_notifications_user'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('clips_created_at_idx'), table_name='clips')
    op.drop_index(op.f('clips_task_id_idx'), table_name='clips')
    op.drop_index(op.f('clips_user_id_idx'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('idx_analytics_sync_clip'), table_name='analytics_sync_log')
    op.drop_index(op.f('idx_analytics_sync_time'), table_name='analytics_sync_log')
    op.drop_table('analytics_sync_log')
    op.drop_index(op.f('idx_ab_tests_status'), table_name='ab_tests')
    op.drop_index(op.f('idx_ab_tests_user'), table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_table('watchdog_events')
    op.drop_table('schema_migrations')
    op.drop_table('account')
    op.drop_index(op.f('idx_clip_performance_clip_id'), table_name='clip_performance')
    op.drop_table('clip_performance')
    op.drop_index(op.f('idx_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('idx_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('idx_scheduled_jobs_next_run'), table_name='scheduled_jobs', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_scheduled_jobs_user'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('idx_sf_user'), table_name='suggestion_feedback')
    op.drop_table('suggestion_feedback')
    op.drop_index(op.f('idx_trend_triggers_user'), table_name='trend_triggers')
    op.drop_table('trend_triggers')
    op.drop_index(op.f('idx_clip_suggestions_clip'), table_name='clip_suggestions')
    op.drop_index(op.f('idx_clip_suggestions_status'), table_name='clip_suggestions')
    op.drop_table('clip_suggestions')
    op.drop_table('session')
    op.drop_table('stripe_webhook_events')
    op.drop_index(op.f('idx_clips_ab_test'), table_name='generated_clips', postgresql_where='(ab_test_id IS NOT NULL)')
    op.drop_index(op.f('idx_clips_instagram_id'), table_name='generated_clips', postgresql_where='(instagram_media_id IS NOT NULL)')
    op.drop_index(op.f('idx_clips_tiktok_id'), table_name='generated_clips', postgresql_where='(tiktok_video_id IS NOT NULL)')
    op.drop_index(op.f('idx_clips_youtube_id'), table_name='generated_clips', postgresql_where='(youtube_video_id IS NOT NULL)')
    op.drop_index(op.f('idx_generated_clips_task_id'), table_name='generated_clips')
    op.drop_index(op.f('idx_generated_clips_thumbnail'), table_name='generated_clips', postgresql_where='(thumbnail_filename IS NOT NULL)')
    op.drop_column('generated_clips', 'caption_template')
    op.drop_column('generated_clips', 'suggested_hashtags')
    op.drop_column('generated_clips', 'social_description')
    op.drop_column('generated_clips', 'render_context')
    op.drop_column('generated_clips', 'translated_text')
    op.drop_column('generated_clips', 'font_style')
    op.drop_column('generated_clips', 'face_detected')
    op.drop_column('generated_clips', 'hook_preview_score')
    op.drop_column('generated_clips', 'creative_meta_json')
    op.drop_column('generated_clips', 'multi_angle_metadata')
    op.drop_column('generated_clips', 'thumbnail_filename')
    op.drop_column('generated_clips', 'status')
    op.drop_column('generated_clips', 'social_title')
    op.drop_index(op.f('idx_processing_cache_source_url'), table_name='processing_cache')
    op.alter_column('sources', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('idx_sources_url'), table_name='sources')
    op.drop_index(op.f('sources_created_at_idx'), table_name='sources')
    op.drop_column('sources', 'url_secondary')
    op.add_column('tasks', sa.Column('include_broll', sa.Boolean(), server_default=sa.text("'false'"), nullable=True))
    op.alter_column('tasks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('tasks', 'source_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('tasks', 'generated_clips_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String(length=36)),
               existing_nullable=True)
    op.alter_column('tasks', 'caption_template',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('tasks', 'target_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'eng'::character varying"))
    op.alter_column('tasks', 'auto_center_face',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'eye_contact_correction',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'split_screen',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_tasks_batch_id'), table_name='tasks', postgresql_where='(batch_id IS NOT NULL)')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_created'), table_name='tasks')
    op.drop_index(op.f('tasks_created_at_idx'), table_name='tasks')
    op.drop_index(op.f('tasks_source_id_idx'), table_name='tasks')
    op.drop_index(op.f('tasks_status_idx'), table_name='tasks')
    op.drop_index(op.f('tasks_user_id_idx'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_source_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'original_filename')
    op.drop_column('tasks', 'progress_message')
    op.drop_column('tasks', 'source_type')
    op.drop_column('tasks', 'error_message')
    op.drop_column('tasks', 'metadata')
    op.drop_column('tasks', 'retry_count')
    op.drop_column('tasks', 'batch_id')
    op.drop_column('tasks', 'progress')
    op.drop_column('tasks', 'local_video_path')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('users', 'default_font_color')
    op.drop_column('users', 'beta_access')
    op.drop_column('users', 'last_reset_date')
    op.drop_column('users', 'default_font_family')
    op.drop_column('users', 'default_font_size')
    op.drop_column('users', 'clips_this_month')
    op.drop_column('users', 'waitlist_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('waitlist_status', sa.VARCHAR(length=20), server_default=sa.text("'approved'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('clips_this_month', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('default_font_size', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('default_font_family', sa.VARCHAR(length=100), server_default=sa.text("'TikTokSans-Regular'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_reset_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('beta_access', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('default_font_color', sa.VARCHAR(length=7), server_default=sa.text("'#FFFFFF'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('users', 'image',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('local_video_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('batch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'youtube'::character varying"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('progress_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_source_id_fkey'), 'tasks', 'sources', ['source_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('tasks_user_id_idx'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('tasks_status_idx'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('tasks_source_id_idx'), 'tasks', ['source_id'], unique=False)
    op.create_index(op.f('tasks_created_at_idx'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('idx_tasks_user_created'), 'tasks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_batch_id'), 'tasks', ['batch_id'], unique=False, postgresql_where='(batch_id IS NOT NULL)')
    op.alter_column('tasks', 'split_screen',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'eye_contact_correction',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'auto_center_face',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'target_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'eng'::character varying"))
    op.alter_column('tasks', 'caption_template',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('tasks', 'generated_clips_ids',
               existing_type=sa.ARRAY(sa.String(length=36)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('tasks', 'source_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tasks', 'include_broll')
    op.add_column('sources', sa.Column('url_secondary', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.create_index(op.f('sources_created_at_idx'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('idx_sources_url'), 'sources', ['url'], unique=False)
    op.alter_column('sources', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_processing_cache_source_url'), 'processing_cache', ['source_url'], unique=False)
    op.add_column('generated_clips', sa.Column('social_title', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'final'::character varying"), autoincrement=False, nullable=False))
    op.add_column('generated_clips', sa.Column('thumbnail_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('multi_angle_metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('creative_meta_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('hook_preview_score', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('face_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('font_style', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('translated_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('render_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('social_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('suggested_hashtags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('generated_clips', sa.Column('caption_template', sa.VARCHAR(length=100), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_generated_clips_thumbnail'), 'generated_clips', ['thumbnail_filename'], unique=False, postgresql_where='(thumbnail_filename IS NOT NULL)')
    op.create_index(op.f('idx_generated_clips_task_id'), 'generated_clips', ['task_id'], unique=False)
    op.create_index(op.f('idx_clips_youtube_id'), 'generated_clips', ['youtube_video_id'], unique=False, postgresql_where='(youtube_video_id IS NOT NULL)')
    op.create_index(op.f('idx_clips_tiktok_id'), 'generated_clips', ['tiktok_video_id'], unique=False, postgresql_where='(tiktok_video_id IS NOT NULL)')
    op.create_index(op.f('idx_clips_instagram_id'), 'generated_clips', ['instagram_media_id'], unique=False, postgresql_where='(instagram_media_id IS NOT NULL)')
    op.create_index(op.f('idx_clips_ab_test'), 'generated_clips', ['ab_test_id'], unique=False, postgresql_where='(ab_test_id IS NOT NULL)')
    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_webhook_events_pkey'))
    )
    op.create_table('session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('session_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey')),
    sa.UniqueConstraint('token', name=op.f('session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('clip_suggestions',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(uuid_generate_v4())::text'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], name=op.f('clip_suggestions_clip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clip_suggestions_pkey'))
    )
    op.create_index(op.f('idx_clip_suggestions_status'), 'clip_suggestions', ['clip_id', 'status'], unique=False)
    op.create_index(op.f('idx_clip_suggestions_clip'), 'clip_suggestions', ['clip_id', 'category', 'sort_order'], unique=False)
    op.create_table('trend_triggers',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('min_virality_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('70.0'), autoincrement=False, nullable=False),
    sa.Column('processing_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('publish_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trigger_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trend_triggers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trend_triggers_pkey'))
    )
    op.create_index(op.f('idx_trend_triggers_user'), 'trend_triggers', ['user_id'], unique=False)
    op.create_table('suggestion_feedback',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('suggestion_feedback_pkey'))
    )
    op.create_index(op.f('idx_sf_user'), 'suggestion_feedback', ['user_id', 'kind'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cron_expression', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('processing_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('publish_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('run_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_clips_generated', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('scheduled_jobs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_jobs_pkey'))
    )
    op.create_index(op.f('idx_scheduled_jobs_user'), 'scheduled_jobs', ['user_id'], unique=False)
    op.create_index(op.f('idx_scheduled_jobs_next_run'), 'scheduled_jobs', ['next_run'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('campaigns',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::character varying'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), server_default=sa.text("'all'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('ab_test_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_index(op.f('idx_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('clip_performance',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('(gen_random_uuid())::character varying'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('watch_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('user_rating', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('clip_performance_campaign_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], name=op.f('clip_performance_clip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clip_performance_pkey'))
    )
    op.create_index(op.f('idx_clip_performance_clip_id'), 'clip_performance', ['clip_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accessToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessTokenExpiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('refreshTokenExpiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('account_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('watchdog_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fix_applied', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('fix_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('watchdog_events_pkey'))
    )
    op.create_table('ab_tests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('original_clip_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'created'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('test_duration_hours', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('winner_variant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('test_accounts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['original_clip_id'], ['generated_clips.id'], name=op.f('ab_tests_original_clip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ab_tests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_tests_pkey'))
    )
    op.create_index(op.f('idx_ab_tests_user'), 'ab_tests', ['user_id'], unique=False)
    op.create_index(op.f('idx_ab_tests_status'), 'ab_tests', ['status'], unique=False)
    op.create_table('analytics_sync_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sync_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('views_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_rate_before', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('engagement_rate_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['generated_clips.id'], name=op.f('analytics_sync_log_clip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_sync_log_pkey'))
    )
    op.create_index(op.f('idx_analytics_sync_time'), 'analytics_sync_log', ['sync_time'], unique=False)
    op.create_index(op.f('idx_analytics_sync_clip'), 'analytics_sync_log', ['clip_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('viral_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thumbs', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clips_pkey'))
    )
    op.create_index(op.f('clips_user_id_idx'), 'clips', ['user_id'], unique=False)
    op.create_index(op.f('clips_task_id_idx'), 'clips', ['task_id'], unique=False)
    op.create_index(op.f('clips_created_at_idx'), 'clips', ['created_at'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_log_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_log_pkey'))
    )
    op.create_index(op.f('idx_notifications_user'), 'notification_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_unread'), 'notification_log', ['user_id', 'read_at'], unique=False, postgresql_where='(read_at IS NULL)')
    op.create_table('verification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_pkey'))
    )
    # ### end Alembic commands ###
