ALTER TABLE "tasks"
ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) NOT NULL DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS "font_family" VARCHAR(100) DEFAULT 'TikTokSans-Regular',
ADD COLUMN IF NOT EXISTS "font_size" INTEGER DEFAULT 24,
ADD COLUMN IF NOT EXISTS "font_color" VARCHAR(7) DEFAULT '#FFFFFF';

CREATE INDEX IF NOT EXISTS "tasks_status_idx" ON "tasks"("status");
